Models/Book.cs
namespace helloweb.Models{
    public class Book{
        public int id { get; set; }
        public string title { get; set; }
        public string  author { get; set; }
        public string  description { get; set; }
        public string  language { get; set; }
        public int pages { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace helloweb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace helloweb.Models{
    public class User{
        [Key]
        public int id { get; set; }
        [MaxLength(50)]
        public string name { get; set; }
        [MaxLength(20)]
        [Required]
        public string username { get; set; }
        [MaxLength(100)]
        [EmailAddress]
        public string email { get; set; }
        [Required] 
        public string password { get; set; }
    }
}

Controllers/BooksController.cs
using System;
using System.Threading.Tasks;
using helloweb.Models;
using helloweb.Services;
using Microsoft.AspNetCore.Mvc;

namespace helloweb.Controllers
{
    public class BooksController : Controller{
        private readonly IBookService _bookService;

        public BooksController(IBookService bookService){_bookService=bookService;}

        public  IActionResult  Index(){
          ViewBag.Book=  _bookService.GetBookById(1);
          ViewBag.Name="Junior";
          return View();
        }
        public  IActionResult GetAllBooks(){
          var data=  _bookService.GetAllBooks();
          return View(data);
        }
        public  IActionResult  GetBook(int id){  
            var book= _bookService.GetBookById(id);

            return View(book);
          }
          public IActionResult AddBook()=> View();
          
          [HttpPost]
          public  IActionResult AddBook(Book book)
          {
              _bookService.AddBook(book);
              return Redirect("GetAllBooks");
          }
          
    }  
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using helloweb.Models;

namespace helloweb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserController.cs
using System.Threading.Tasks;
using helloweb.Data;
using helloweb.Services;
using Microsoft.AspNetCore.Mvc;

namespace aspweb.Controllers
{
    public class UserController : Controller
    {
        // private readonly IUserService _userService;

        // public UserController(IUserService userService)
        // {
        //     _userService = userService;
        // }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            // TODO: Your code here
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterUser user)
        {
        //    await  _userService.CreateUser(user);
            
            return View();
        }


        public IActionResult Login()
        {
            // TODO: Your code here
            return View();
        }
        
        
    }
}

Views/Books/AddBook.cshtml
@model Book

<form class="card p-3 m-3 " enctype="multipart/form-data" method="post" action="">
    <div class="mb-3">
        <label asp-for="title" class="form-label">Title</label>
        <input type="text" asp-for="title" class="form-control" id="" required  placeholder="title">
    </div>
     <div class="mb-3">
        <label for="" class="form-label">Author</label>
        <input type="text" asp-for="author" class="form-control" id="" required placeholder="John Doe">
    </div>
     <div class="mb-3">
        <label for="" class="form-label">Pages</label>
        <input type="number" asp-for="pages" class="form-control" id="" required placeholder="500">
    </div>
    <div class="mb-3">
        <label asp-for="language">Language</label>
        <select class="form-control form-select " asp-for="language" aria-label="Default select example">
            <option value="English" >English</option>
            <option value="Spanish">Spanish</option>
            <option value="French">French</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Description</label>
        <textarea asp-for="description" class="form-control" required id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <div class="input-group mb-3">
        <label class="input-group-text" for="inputGroupFile01">Upload</label>
        <input type="file" class="form-control" id="inputGroupFile01" />
    </div>
    <button type="submit" class="btn btn-primary w-75 m-3 mx-auto">ADD BOOK</button>
</form>

Views/Books/GetAllBooks.cshtml
@model List<Book>
@{
    ViewData["Title"]="All Books";
}
<div class="container ">
    <div class="row mx-auto">
        @foreach (var book in Model)
        {
           <div class="card m-2  " style="width: 18rem;">
                <img src="~/images/book.jpeg" class="card-img-top" alt="">
                <div class="card-body">
                    <h4 class="card-title">@book.title</h4>
                    <p class="card-text">This ia a small description about the book in which user reads and understand.</p>
                    <div class=" d-flex justify-content-between align-items-center">
                        <small class="text-muted">By @book.author</small>
                        <a  href="/books/getbook/@book.id" class="btn btn-dark">View more</a>
                    </div>
                </div>
            </div> 
        }
        
    </div>
</div>

Views/Books/GetBook.cshtml
@model Book
@{
    ViewData["Title"]="Book";
}

<div class="container">
    <div class="row mx-auto mt-5">
        <img src="~/images/homebook.jpeg" class="img-fluid col" style="max-height: 300px; max-width:400px;" alt="">
        <div class="text ml-2  text-dark col" >
            <h3 class="text mb-3">@Model.title</h3>
            <small class="text-primary"> By @Model.author </small>
            <br>
            <span class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur quaerat laboriosam, adipisci in neque rerum facere vitae sequi repudiandae vero nulla debitis tempora expedita, reiciendis ipsa distinctio iste voluptate fuga?</span>
           <br>
            <button class="btn btn-outline-primary m-2">Read Now</button>
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>cartegory - </b> Nature</li>
                    <li class="list-group-item"><b>Pages - </b> @Model.pages</li>
                    <li class="list-group-item"><b>Languge - </b> @Model.language</li>
                </ul>
            </div>
            
        </div>

    </div>
    

</div>

Views/Books/Index.cshtml
@{
    ViewData["Title"]="BOOKS";
}

<div class="container w-100">
    <div class="card bg-dark">
        <p class="text-light text-center p-3 h2"> Hello @ViewBag.Name this card is on books page ! </p>
        <br>
        <span class="text-center text-light" > @DateTime.Now  </span>
        <br>
        <span class="text-center text-white">  a sample viewbag book @ViewBag.Book.title by @ViewBag.Book.author </span>
        @{
            int a=20;
        }
        <span class="m-2 text-light">@a</span> <span class="m-2 text-light">Twitter handle @@muchirajunior</span>
    </div>

</div>

<div class="container mt-5">
    <div class="card mx-auto bg-success text-light text-center p-3">
        <h2>This is razor conditional statements card</h2>
        <br>
        @{
            int number =30;
        }
        @if(number<20){
            <p>The number is smaller @number</p>
        }else{
           <p>The number is bigger @number</p> 
        }
        <!-- a ternary operation-->
        @(number==20 ? number++ : number--)
    </div>

    <div class="container mt-5">
        <div class="card float-end bg-danger text-light p-3">
            <h2 class="text-center"> Custom for loop in Razor </h2>
            @for(int i=0;i<4; i++){
                <span>Item number @i</span>
            }
            <br> <br>
            <h2 class="text-center">Custom foreach loop in Razor</h2>
            @{
                List<string> names=new List<string>(){"John","Junior","Martha","Alex"};
            }
            @foreach (var name in names)
            {
                <span>Learner number @(names.IndexOf(name)+1) is @name</span>
            }
        </div>
    </div>

    <div class="container mt-3">
        <div class="card mx-auto" style="width: 18rem;">
            <img src="images/mcuapp.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
         </div>
    </div>


</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web applications with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - helloweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white  box-shadow mb-3 mt-1">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">helloweb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="GetAllBooks">All Books</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="AddBook">Add Book</a>
                        </li>
                    </ul>
                    <a asp-action="Register" asp-controller="User" class="btn btn-outline-success m-2" >create account</a>
                    <a asp-controller="User" asp-action="Login" class="btn btn-primary m-2">login here</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center">
            HelloWeb Sample   &copy; 2021 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Index.cshtml
<div class="container">
    USER PAGE
</div>

Views/User/Login.cshtml
<div class="container">
  <div class="row">

    <img src="~/images/signup.png" class="img-fluid col" style="max-width:400px; min-width:300px;" alt=""/>

      <form class="card border-0 p-3 shadow mx-auto col" style="min-width: 300px;" method="post" action="">
        <h2 class="text text-muted mb-5">User Sign In</h2>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" name="email" class="form-control shadow border-0" id="exampleInputEmail1" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control shadow border-0" id="exampleInputPassword1">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" name="remember" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Remember Me</label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

  </div>

</div>

Views/User/Register.cshtml
@model helloweb.Data.RegisterUser
<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" asp-for="Username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" asp-for="Password" class="form-control" id="exampleInputPassword1">
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Confirm Password</label>
    <input type="password" asp-for="ConfirmPassword" class="form-control" id="exampleInputPassword1">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>